################################################################
# edit wildcards - comment out unwanted options

# project name
project: snake

# sample table path
sample_table: /scratch/users/k2142172/outputs/verstockt_ibd/verstockt_ibd_sample_table.tab

# samples IDs
#sample:
#    - ERR3262399
#    - ERR3262400

# build - default GRCh38
build: 
    - GRCh38
#    - GRCm39

# paired end - default yes
paired:
    - yes
#    - no

# strand - default unstranded 0, forward 1, reverse 2
strand:
    - 0
#    - 1
#    - 2

# aligner - default star
aligner:
    - STAR
#    - kallisto

# base directory
base_dir: /scratch/users/k2142172



#####################################################################
# constant wildcards

# tools
fastqc: /scratch/users/k2142172/packages/FastQC/fastqc
multiqc: /scratch/users/k2142172/packages/anaconda3/envs/r4/bin/multiqc
star: /scratch/users/k2142172/packages/STAR-2.7.8a/bin/Linux_x86_64_static/STAR
samtools: /scratch/users/k2142172/packages/samtools-1.11/bin/samtools
featurecounts: /scratch/users/k2142172/packages/subread-2.0.1-Linux-x86_64/bin/featureCounts

# star parameters

# feature counts parameters
feature: gene_id
